version: "3.8"
services:
   eureka-server:
      build: ./movie-services-registry
      container_name: eureka-server
       # you can use command `docker compose up --build` to build and run the image.
      ports:
         - "8761:8761"
      environment:
         - server.port=8761
         - spring.application.name=movie-services-registry
         - eureka.client.register-with-eureka=false
         - eureka.client.fetch-registry=false

   payment-service:
      build: ./payment-service
      container_name: payment-service
      ports:
         - "9090:9090"
      environment:
         - server.port=9090
         - spring.application.name=payment-service
         - eureka.client.register-with-eureka=true
         - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

   booking-service:
      build: ./booking-service
      container_name: booking-service
      ports:
         - "8080:8080"
      environment:
         - server.port=8080
         - spring.application.name=booking-service
         - eureka.client.register-with-eureka=true
         - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

   notification-service:
      build: ./notification-service
      container_name: notification-service
      ports:
         - "7070:7070"
      environment:
         - server.port=7070
         - spring.application.name=notification-service
         - eureka.client.register-with-eureka=true
         - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
